# Generated by Django 2.0.6 on 2018-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('animal_weigth', '0005_auto_20180701_1703')]

    operations = [
        migrations.AlterField(
            model_name='farmmodel',
            name='token',
            field=models.CharField(
                default='46709a8b25fc81cb2736236221408ffe338037771de180646568bbff2d2d',
                max_length=30,
                unique=True,
                verbose_name='token',
            ),
        )
    ]
