# Generated by Django 2.0.6 on 2018-07-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('animal_weigth', '0006_auto_20180701_1704')]

    operations = [
        migrations.AlterField(
            model_name='farmmodel',
            name='token',
            field=models.CharField(
                default='7ee503448179d7c3c6f515de805a04be176744ad541132a0106ac71c6fb0',
                max_length=30,
                unique=True,
                verbose_name='token',
            ),
        )
    ]
